#sdk: "d:/motorolarhomobilesuite2.0.5/ruby/lib/ruby/gems/1.9.1/gems/rhodes-3.3.3"
sdkversion: 3.3.3
name: RhoMobileApplication1
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.rhomobileapplication1
  BundleURLScheme: rhomobileapplication1
wp:
  productid: 'f93e5470-5a5d-0130-f945-001e379e67db'
symbian:
  uid: '0xe3fbf139'
android:
  version: 2.1

extensions: ["json", "another-extension"]
